/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.*;
import Conexao.ModuloConexao;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public Login() {
    initComponents();
    conexao = ModuloConexao.conector();
    System.out.println(conexao);
    System.out.println("conectado :)");
    
        if (conexao != null){
            lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/database_status-c.png")));
        }else{
            lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/database_status-x.png")));
        }
    }
    
  public void Logar(){
      String sql = "select *  from usuarios where nome=? and senha=?";
      try {
          pst = conexao.prepareStatement(sql);
          pst.setString(1, txtUsuarios.getText());
          pst.setString(2, TextoSenha.getText());
          rs = pst.executeQuery();
          if (rs.next()){
              Tprincipal principal = new Tprincipal();
              principal.setVisible(true);
              this.dispose();
              conexao.close();
          }else{
           JOptionPane.showMessageDialog(null, "O Usuario e/ou senha invalido(s)");
          }
          
      } catch (Exception e) {
          JOptionPane.showMessageDialog(null, e);
      }
  }
  
           


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnLogar = new javax.swing.JButton();
        CheckBox = new javax.swing.JCheckBox();
        TextoSenha = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtUsuarios = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(200, 200));
        setPreferredSize(new java.awt.Dimension(476, 358));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMaximumSize(new java.awt.Dimension(300, 300));
        jPanel6.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel6.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel6.setVerifyInputWhenFocusTarget(false);
        jPanel6.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(24, 31, 50));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Desenvolvido por VictoryBay");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel3);
        jPanel3.setBounds(0, 290, 260, 27);

        jPanel2.setBackground(new java.awt.Color(24, 31, 50));
        jPanel2.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo_Rm-invert.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 0, 300, 120);

        jPanel6.add(jPanel2);
        jPanel2.setBounds(110, 0, 390, 110);

        jPanel1.setBackground(new java.awt.Color(159, 4, 2));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        btnLogar.setBackground(new java.awt.Color(159, 4, 2));
        btnLogar.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnLogar.setForeground(new java.awt.Color(255, 255, 255));
        btnLogar.setText("Entrar");
        btnLogar.setBorder(null);
        btnLogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarActionPerformed(evt);
            }
        });
        btnLogar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLogarKeyPressed(evt);
            }
        });
        jPanel1.add(btnLogar);
        btnLogar.setBounds(290, 240, 70, 30);

        CheckBox.setBackground(new java.awt.Color(159, 4, 2));
        CheckBox.setForeground(new java.awt.Color(255, 255, 255));
        CheckBox.setText("Mostrar senha");
        CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(CheckBox);
        CheckBox.setBounds(90, 240, 120, 30);

        TextoSenha.setBackground(new java.awt.Color(24, 31, 50));
        TextoSenha.setForeground(new java.awt.Color(255, 255, 255));
        TextoSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(24, 31, 50), 4));
        TextoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(TextoSenha);
        TextoSenha.setBounds(89, 200, 270, 30);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Senha");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 180, 70, 16);

        txtUsuarios.setBackground(new java.awt.Color(24, 31, 50));
        txtUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(24, 31, 50), 4));
        txtUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuarios);
        txtUsuarios.setBounds(89, 150, 270, 30);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuário");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 130, 120, 16);

        lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/database_status-x.png"))); // NOI18N
        lblStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblStatus);
        lblStatus.setBounds(400, 260, 40, 30);

        jPanel6.add(jPanel1);
        jPanel1.setBounds(10, 10, 440, 300);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ArtLogoVitória.jpg"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.add(jLabel5);
        jLabel5.setBounds(-830, -380, 1650, 1060);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 0, 500, 360);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (CheckBox.isSelected()) {
            TextoSenha.setEchoChar((char) 0);
        } else {
            TextoSenha.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarActionPerformed
        Logar();
    }//GEN-LAST:event_btnLogarActionPerformed

    private void btnLogarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLogarKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER){
            
            Logar();
        }
    }//GEN-LAST:event_btnLogarKeyPressed

    private void TextoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox;
    private javax.swing.JPasswordField TextoSenha;
    private javax.swing.JButton btnLogar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtUsuarios;
    // End of variables declaration//GEN-END:variables
}
