package View;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author aless
 */
public class Tpropriedades extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tpropriedades
     */
    public Tpropriedades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(531, 351));
        setNormalBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(531, 351));
        setVisible(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(242, 241, 241));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(243, 235, 235), 2, true));
        jPanel1.setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(159, 4, 2));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel13.setText("Esse software gerencia o cadastro de clientes, organizaros seus pedidos, monitora o");
        jPanel8.add(jLabel13);
        jLabel13.setBounds(10, 10, 551, 17);

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel14.setText("acompanhamento de pedidos.");
        jPanel8.add(jLabel14);
        jLabel14.setBounds(10, 30, 190, 17);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("Versão: 2.0");
        jPanel8.add(jLabel27);
        jLabel27.setBounds(390, 100, 100, 16);

        jPanel21.setBackground(new java.awt.Color(159, 4, 2));
        jPanel21.setLayout(null);

        jLabel49.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Logout");
        jLabel49.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel49MouseClicked(evt);
            }
        });
        jPanel21.add(jLabel49);
        jLabel49.setBounds(440, 3, 59, 30);

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Desenvolvido por VictoryBay");
        jPanel21.add(jLabel15);
        jLabel15.setBounds(200, 10, 153, 15);

        jPanel8.add(jPanel21);
        jPanel21.setBounds(0, 130, 600, 35);

        jTabbedPane1.addTab("Sobre", jPanel8);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        jLabel21.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel21.setText("vix.bay.group@email.com");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(20, 80, 137, 15);

        jLabel19.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel19.setText("Caso haja alguma dúvida sobre o sistema, temos um canal de suporte ");
        jPanel6.add(jLabel19);
        jLabel19.setBounds(20, 10, 450, 18);

        jLabel22.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel22.setText("vixbay.com.br");
        jPanel6.add(jLabel22);
        jLabel22.setBounds(20, 100, 137, 15);

        jLabel20.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel20.setText("(27) 90000-0000/ (27) 90000-0000");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(20, 60, 190, 15);

        jLabel24.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel24.setText("Basta se comunicar através de uma das formas de contato abaixo:");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(20, 30, 421, 18);

        jPanel17.setBackground(new java.awt.Color(159, 4, 2));
        jPanel17.setLayout(null);

        jLabel45.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Logout");
        jLabel45.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel45MouseClicked(evt);
            }
        });
        jPanel17.add(jLabel45);
        jLabel45.setBounds(440, 3, 59, 30);

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Desenvolvido por VictoryBay");
        jPanel17.add(jLabel11);
        jLabel11.setBounds(200, 10, 153, 15);

        jPanel6.add(jPanel17);
        jPanel17.setBounds(0, 130, 600, 35);

        jTabbedPane1.addTab("Suporte", jPanel6);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jPanel19.setBackground(new java.awt.Color(159, 4, 2));
        jPanel19.setLayout(null);

        jLabel47.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Logout");
        jLabel47.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel47MouseClicked(evt);
            }
        });
        jPanel19.add(jLabel47);
        jLabel47.setBounds(440, 3, 59, 30);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Desenvolvido por VictoryBay");
        jPanel19.add(jLabel9);
        jLabel9.setBounds(200, 10, 153, 15);

        jPanel4.add(jPanel19);
        jPanel19.setBounds(0, 130, 600, 35);

        jLabel16.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel16.setText(" sempre como meta ser a peça chave para a evolução de sua empresa.");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(10, 50, 408, 23);

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel6.setText("de cada cliente, para assim satisfazer as necessidades de cada cliente/usuário, tendo");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 30, 491, 17);

        jLabel18.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel18.setText("A VixBay é uma empresa que tem como objetivo criar softwares baseados nos perfis ");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(10, 10, 490, 17);

        jTabbedPane1.addTab("Quem somos", jPanel4);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 130, 520, 190);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo Rm.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 40, 300, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ArtLogoVitória.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-810, -400, 1330, 710);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 519, 326);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel47MouseClicked
        // TODO add your handling code here:
        Login dashboard = new Login();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel47MouseClicked

    private void jLabel45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel45MouseClicked
        // TODO add your handling code here:
        Login dashboard = new Login();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel45MouseClicked

    private void jLabel49MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel49MouseClicked
        // TODO add your handling code here:
        Login dashboard = new Login();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel49MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
